### ISSUE TITLE
Update Azure Devops config to work with .NET 5

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#3419]

**Comment by simonauner** [comment]
Sorry for commenting on such an old thread, but my takeaway from this is that it should be possible to send NET5-projects for SonarCloud analysis? Yet our fails. We have since before added a build step where we downgrade to dotnet core 2.2 in order to run the SonarCloud task:

```yaml
  - task: UseDotNet@2
    displayName: 'Switch to .net 2.2.x SDK for Sonar cloud analyzer'
    inputs:
      packageType: sdk
      version: 2.2.x

  - task: SonarCloudAnalyze@1
    displayName: Send for SonarCloud Analysis

  - task: UseDotNet@2
    displayName: 'Switch to .net ${{ variables.netSdkVersion }} SDK'
    inputs:
      packageType: sdk
      version: ${{ variables.netSdkVersion }}
```

where `netSdkVersion` is `5.0.x`


I tried to remove it, but got the following error:
![image](https://user-images.githubusercontent.com/1343979/126789261-eabc4a76-d226-4f6b-bea4-a697f263e1d0.png)

Are we missing something here?
