### ISSUE TITLE
SE: Enum members are not tracked symbols

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#7200]
S2259 test cases seems to handle enum members as symbols instead of constants and learn values from `handler`

https://github.com/SonarSource/sonar-dotnet/pull/7187#discussion_r1190884960
```
public enum Helper
{
    A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P
}

class NullPointerDereference
{

    public static void OrConstraint()
    {
        var helper = Helper.A;
        object o = null;
        if (helper == Helper.A | helper == Helper.B | helper == Helper.C | helper == Helper.D
            | helper == Helper.E | helper == Helper.F | helper == Helper.G | helper == Helper.H
            | helper == Helper.I | helper == Helper.A | helper == Helper.B | helper == Helper.C
            | helper == Helper.D | helper == Helper.E | helper == Helper.F | helper == Helper.G
            | helper == Helper.H | helper == Helper.I | helper == Helper.A | helper == Helper.B
            | helper == Helper.C | helper == Helper.D | helper == Helper.E | helper == Helper.F
            | helper == Helper.G | helper == Helper.H | helper == Helper.I | helper == Helper.J)
        {
            o.ToString(); // FN (old engine: FN, the condition state generation is too big to explore all constraint combinations)
        }
    }

}
```
**Before** #7187 
```
---------- Processing ----------
Block #1, Operation #9, BinaryOperation: helper == Helper.A
Symbols:
A: NotNull
helper: NotNull, Number 0
o: Null
Operations:
FieldReferenceOperation: Helper.A: NotNull
LocalReferenceOperation: helper: NotNull, Number 0

    ---------- Enqueuing ----------
    Block #1, Operation #10, LocalReferenceOperation: helper
    Symbols:
    A: NotNull
    helper: NotNull, Number 0
    o: Null
    Operations:
    BinaryOperation: helper == Helper.A: NotNull
    FieldReferenceOperation: Helper.A: NotNull
    LocalReferenceOperation: helper: NotNull, Number 0
```
**After** #7187 
```
---------- Processing ----------
Block #1, Operation #9, BinaryOperation: helper == Helper.A
Symbols:
A: NotNull
helper: NotNull, Number 0
o: Null
Operations:
FieldReferenceOperation: Helper.A: NotNull
LocalReferenceOperation: helper: NotNull, Number 0

    ---------- Enqueuing ----------
    Block #1, Operation #10, LocalReferenceOperation: helper
    Symbols:
    A: NotNull, Number 0
    helper: NotNull, Number 0
    o: Null
    Operations:
    BinaryOperation: helper == Helper.A: NotNull, True
    FieldReferenceOperation: Helper.A: NotNull
    LocalReferenceOperation: helper: NotNull, Number 0
    
    ---------- Enqueuing ----------
    Block #1, Operation #10, LocalReferenceOperation: helper
    Symbols:
    A: NotNull
    helper: NotNull, Number 0
    o: Null
    Operations:
    BinaryOperation: helper == Helper.A: False, NotNull
    FieldReferenceOperation: Helper.A: NotNull
    LocalReferenceOperation: helper: NotNull, Number 0
    

```
